Create UI Home
desarrolladorSLP/teckers-ios-app pull request #47
Opened 2019-09-11 18:22 UTC by maggie97

Creation of UI Home 
Interaction with the backend with Charles

2019-09-12 05:03 UTC, cortestavo requested changes

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/AuthRouter.swift
> +    case getMessages
messages endpoint should be implemented in a different router enum

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/AuthRouter.swift
> +                    let username = pListData["USER"] as! String
use enum case instead of hard coded string

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/AuthRouter.swift
> +                    let username = pListData["USER"] as! String
same thing in next line

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/Authentication.swift
> +    func backendMessagesRequest(success : @escaping (_ JSON : [String : Any]) -> Void){
this logic should be implemented in a different class

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/Color.swift
> +    static var morado : UIColor = UIColor(red: 93/255, green: 92/255, blue: 160/255, alpha: 1)
english please :)

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +extension HomeController : UITableViewDataSource, UITableViewDelegate{
create 2 extensions, each one implementing a single protocol

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "MessageCell", for: indexPath) as! MessageCell
avoid hard coded strings, could be better to have an enum case or allow MessageCell class to be aware about it's own reusable identifier instead

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/Message.swift
> +    var date : String
I think it could be better to have date properties as Date

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +    func today() -> String{
this func doesn't belong here, maybe it should be implemented as an extension of Date?

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +        self.backendInteraction.backendMessagesRequest  { (response) in
capturing self

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +            listJSON = JSON["highPriorityMessages"] as? [ Any]
avoid hard coded strings

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +            listJSON = JSON["lowPriorityMessages"] as? [Any]
avoid hard coded strings

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +        guard let List = listJSON else{
List should be came Case

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +    func pullAllMessagesOf(priority: Bool, in list: [Any]){
consider to receive an array of MessageUser to avoid mapping logic here

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesLists.swift
> +    func createMessage(item : [String : Any] , priority : Bool) -> MessagesUser?{
this func might belong to MessageUser class as a convenience initializer

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesTableViewDelegate.swift
> +//    var reload : () -> Void
remove comment

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesTableViewDelegate.swift
> +    func scrollViewDidScroll(_ scrollView: UIScrollView) {
methods shouldn't be empty

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/MessagesTableViewDelegate.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "MessageCell", for: indexPath) as! MessageCell
avoid hard coded strings

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/PrincipalNavigationItem.swift
> +class PrincipalNavigationItem: UINavigationItem {
maybe main instead of principal?

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/PrincipalNavigationItem.swift
> +    @objc func tapButton(){
is this test code?

2019-09-12 05:03 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +            self.messageTableView.reloadData()
we need to be sure this code is always running in the main thread

2019-09-13 16:36 UTC, maggie97 commented on teckers/teckers/PrincipalNavigationItem.swift
> +    @objc func tapButton(){
yes

2019-09-20 04:18 UTC, cortestavo requested changes

2019-09-20 04:18 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +        messagesList = []
this var is already a []

2019-09-20 04:18 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +                DispatchQueue.main.async {
consider to use didSet to reload data instead

2019-09-20 04:18 UTC, cortestavo commented on teckers/teckers/Info.plist
> +		<key>NSAllowsArbitraryLoads</key>
are we calling non secure urls?

2019-09-20 04:18 UTC, cortestavo commented on teckers/teckers/MessageCell.swift
> +    static var NameCell = "MessageCell"
we might use a computed property instead of the use of a static property

2019-09-20 04:18 UTC, cortestavo commented on teckers/teckers/MessageCell.swift
> +            if let urlImage = URL(string: userFriend.imageURL){
we should use a default image and also ... how is this image retrieved?? sync or async?

2019-09-24 18:08 UTC, cortestavo approved these changes

2019-09-24 18:08 UTC, merged