Error layer
desarrolladorSLP/teckers-ios-app pull request #54
Opened 2019-10-10 00:14 UTC by maggie97

2019-10-10 16:48 UTC, cortestavo requested changes

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +            if let info = NetworkError.instance.getInformation(for: 401){
avoid to use raw values, use an enum instead

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/HomeController.swift
> +        let alertNotification = Alert(title: "Error", massage: message, type: 0)
type doesn't exist anymore

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkError.swift
> +//                NetworkError.delegate?.dismiss()
remove comment

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkError.swift
> +     func getInformation( for statusCode: Int) ->  (message: String, type: Int)?{
create an enum for http responses

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkError.swift
> +        case 401:
use enum case instead of int hardcoded value

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkError.swift
> +     func getAction(for statusCode: Int) -> () -> Void {
use an enum case instead an int value

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkHandler.swift
> +            NetworkError.instance.getAction(for: 600)()
use an enum case instead an int value

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkHandler.swift
> +                NetworkError.instance.getAction(for: -1)()
use an enum case instead an int value

2019-10-10 16:48 UTC, cortestavo commented on teckers/teckers/NetworkHandler.swift
> +                case 100..<400:
verify if this case is necessary

2019-10-14 16:40 UTC, chirica2501 approved these changes

2019-10-14 16:41 UTC, merged