Event Assistance
desarrolladorSLP/teckers-ios-app pull request #55
Opened 2019-10-10 03:56 UTC by chirica2501

2019-10-10 17:13 UTC, cortestavo requested changes

2019-10-10 17:13 UTC, cortestavo commented on teckers/teckers/Alert.swift
> +                if response == OK.statusOK.rawValue || response == TypesNetworkErrors.confict.rawValue {
use a more descriptive name for the enum (OK is not ok)

2019-10-10 17:13 UTC, cortestavo commented on teckers/teckers/Alert.swift
> +        alert.addAction(UIAlertAction(title: "No🙁", style: .default , handler: { (UIAlertAction) in
use nil if the completion handler is not needed

2019-10-10 17:13 UTC, cortestavo commented on teckers/teckers/SessionController.swift
> +            let sessionCurrent = collectionView.dequeueReusableCell(withReuseIdentifier: Cell.SessionCell.rawValue, for: indexPath) as! SessionCell
should be currentSession

2019-10-10 17:13 UTC, cortestavo commented on teckers/teckers/SessionRouter.swift
>      var parameters: Parameters? {
remove parameters

2019-10-11 19:02 UTC, maggie97 approved these changes

2019-10-12 15:59 UTC, merged